# This file containes password for the root user for the VM. If you 
# add the passwords in clear-text, you may encrypt this file using the 
# ansible-vault command to protect the passwords (alternative is to 
# use -e "vm_root_passwd=XXX" in CLI:
#
#     $ ansible-vault encrypt default_vars.yml
#
# For Oracle Linux Automation Manager GUI:
#     configure password in Vault and use Vault in template

# Variables used for VM configuration:

olvm_cluster: Default
olvm_template: OL9U4_x86_64-olvm-b234
vm_ram: 1024MiB
vm_cpu: 2

# Variables used for cloud-init:

vm_root_passwd: CHANGE_ME
vm_dns: 192.168.1.3
vm_dns_domain: demo.local
vm_gateway: 192.168.1.1
vm_netmask: 255.255.255.0
vm_timezone: Europe/Amsterdam
vm_user: opc
vm_user_sshpubkey: "ssh-rsa AAAA...<YOUR KEY HERE>...hj8= "
