---
- hosts: olvm
  become: yes
  become_method: sudo
  gather_facts: yes


  vars_files:
    - default_vars.yml

  tasks:

    - name: Login to OLVM manager
      ovirt_auth:
        url: "{{ lookup('env', 'OVIRT_URL') }}"
        username: "{{ lookup('env', 'OVIRT_USERNAME') }}"
        password: "{{ lookup('env', 'OVIRT_PASSWORD') }}"
        ca_file: "{{ olvm_cafile | default('/etc/pki/ovirt-engine/ca.pem') }}"
        insecure: "{{ olvm_insecure | default(true) }}"
      tags:
        - always

    - name: Create Virtual Machine
      ovirt.ovirt.ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "{{ item }}"
        template: "{{ olvm_template }}"
        cluster: "{{ olvm_cluster | default('Default') }}"
        memory: "{{ hostvars[item]['vm_ram'] | default('1024MiB') }}"
        cpu_sockets: "{{ hostvars[item]['vm_cpu'] | default('1')  }}"
        high_availability: true
        state: running
        wait: yes
        cloud_init:
          host_name: "{{ hostvars[item]['vm_name'] + '.' + vm_dns_domain }}"
          root_password: "{{ vm_root_passwd }}"
          user_name: "{{ vm_user }}"
          authorized_ssh_keys: "{{ vm_user_sshpubkey }}"
          dns_servers: "{{ vm_dns }}"
          dns_search: "{{ vm_dns_domain }}"
          nic_name: "{{ vm_nicname | default('eth0') }}"
          nic_boot_protocol: static
          nic_ip_address: "{{ hostvars[item]['vm_ip_address'] }}"
          nic_gateway: "{{ vm_gateway }}"
          nic_netmask: "{{ vm_netmask }}"
          timezone: "{{ vm_timezone }}"
          custom_script: |
            runcmd:
              - hostnamectl set-hostname {{ hostvars[item]['vm_name'] + '.' + vm_dns_domain }}
              - yum -y remove cloud-init
        wait: true
      loop: "{{ groups['instances'] }}"

    - name: Cleanup OLVM auth token
      ovirt.ovirt.ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
