---
- hosts: all
  become: yes

  tasks:

  - name: add user account with access to sudo
    user:
      name: "{{ username }}"
      password: "{{ user_default_password | password_hash('sha512') }}"
      comment: Ansible created user
      groups: wheel
      append: yes
      update_password: on_create

  - name: set authorized key for user using local public key file
    ansible.posix.authorized_key:
      user: "{{ username }}"
      state: present
      key: "{{ lookup('file', '{{ ssh_keyfile }}') }}"


  - name: set user with passwordless sudo access
    lineinfile:
      path: '/etc/sudoers.d/{{ username }}'
      regexp: '{{ username }} ALL='
      line: '{{ username}} ALL=(ALL:ALL) NOPASSWD: ALL'
      state: present
      create: yes

# Add passwordless ssh between hosts

  - name: generate a unique OpenSSH keypair for passwordless ssh
    community.crypto.openssh_keypair:
      path: '/home/{{ username }}/.ssh/id_olam_rsa'
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: '0700'
    when: ( inventory_hostname == groups["control_nodes"][0] )

  - name: fetch the unique OpenSSH private key
    run_once: yes
    fetch:
      src: '/home/{{ username }}/.ssh/id_olam_rsa'
      dest: buffer/
      flat: yes
    when: ( inventory_hostname == groups["control_nodes"][0] )

  - name: fetch the unique OpenSSH public key
    run_once: yes
    fetch:
      src: '/home/{{ username }}/.ssh/id_olam_rsa.pub'
      dest: buffer/
      flat: yes
    when: ( inventory_hostname == groups["control_nodes"][0] )

  - name: copy unique private key
    ansible.builtin.copy:
      src: buffer/id_olam_rsa
      dest: '/home/{{ username }}/.ssh/id_olam_rsa'
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: '0600'
    when: ( inventory_hostname != groups["control_nodes"][0] )

  - name: copy unique public key
    ansible.builtin.copy:
      src: buffer/id_olam_rsa.pub
      dest: '/home/{{ username }}/.ssh/id_olam_rsa.pub'
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: '0600'
    when: ( inventory_hostname != groups["control_nodes"][0] )

  - name: set authorized key for passwordless ssh using local public key file
    authorized_key:
      user: "{{ username }}"
      state: present
      key: "{{ lookup('file', 'buffer/id_olam_rsa.pub') }}"

  - name: set authorized key for passwordless ssh using local public key file
    authorized_key:
      user: opc
      state: present
      key: "{{ lookup('file', 'buffer/id_olam_rsa.pub') }}"

# Install required packages on all hosts

- hosts: control_nodes,execution_nodes,db_nodes
  collections:
    - ansible.posix
    - community.general
    - community.postgresql
    - community.crypto
  become: yes

  tasks:

    - name: install Oracle EPEL repository
      dnf:
        name: oracle-epel-release-el8
        state: present
      when:
        - ansible_facts['distribution_major_version'] == '8'

    - name: install version lock plugin
      dnf:
        name: python3-dnf-plugin-versionlock
        enablerepo: ol8_developer_EPEL
        state: present

    - name: version lock python3-click
      community.general.yum_versionlock:
        state: present
        name: python3-click

    - name: install additional packages for ansible
      dnf:
        name:
          - python3-psycopg2
          - python3-pyOpenSSL
          - python3-pip
        enablerepo: ol8_developer_EPEL
        state: latest

    - name: install pexpect
      pip:
        name: pexpect
      environment: "{{ pip_proxy_env }}"

  environment: "{{ proxy_env }}"

# Configure remote database

- hosts: db_nodes
  collections:
    - ansible.posix
    - community.general
    - community.postgresql
    - community.crypto
  become: yes

  vars:
    db_node_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

  tasks:

    - name: enable the PostgreSQL 13 module stream
      copy:
       dest: /etc/dnf/modules.d/postgresql.module
       content: |
         [postgresql]
         name=postgresql
         stream=13
         profiles=
         state=enabled
      when:
        - ansible_distribution_major_version | int >= 8

    - name: install the database
      dnf:
        name: postgresql-server
        state: present
      environment: "{{ proxy_env }}"

    - name: ensure postgresql data directory exists
      file:
        path: "/var/lib/pgsql/data"
        owner: "postgres"
        group: "postgres"
        state: directory
        mode: 0700

    - name: check if postgresql is initialized
      stat:
        path: "/var/lib/pgsql/data/PG_VERSION"
      register: pgdata_dir_version

    - name: initialize postgresql database
      command: "postgresql-setup --initdb"
      when: not pgdata_dir_version.stat.exists
      become_user: postgres

    - name: change database password storage encryption
      ansible.builtin.replace:
        path: /var/lib/pgsql/data/postgresql.conf
        regexp: '^#password_encryption.*'
        replace: 'password_encryption = scram-sha-256'

    - name: Enable and start postgresql.service
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: create awx postgresql user
      community.postgresql.postgresql_user:
        name: awx
        password: "{{ awx_pguser_password }}"
        role_attr_flags: NOSUPERUSER
      become_user: postgres

    - name: create awx postgresql db
      community.postgresql.postgresql_db:
        name: awx
        owner: awx
      become_user: postgres

    - name: update host-based authentication
      ansible.builtin.lineinfile:
        path: /var/lib/pgsql/data/pg_hba.conf
        line: "host  all  all 0.0.0.0/0 scram-sha-256"

    - name: set the database listening address
      ansible.builtin.lineinfile:
        path: /var/lib/pgsql/data/postgresql.conf
        insertbefore: '^#port = 5432'
        line: "listen_addresses = '{{ db_node_ip }}'"

    - name: set firewall port rules for db
      ansible.posix.firewalld:
        zone: public
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - 5432/tcp

    - name: restart the database
      systemd:
        name: postgresql
        state: restarted

# Configure OLAM 2.2 hosts

- hosts: control_nodes,execution_nodes
  collections:
    - ansible.posix
    - community.general
    - community.postgresql
    - community.crypto
  become: yes

  tasks:

    - name: install Oracle Linux Automation Manager repository
      dnf:
        name: oraclelinux-automation-manager-release-el8-2.2
        state: present
      environment: "{{ proxy_env }}"

    - name: disable Oracle Linux Automation Manager 1.0 repository
      ini_file:
        path: "/etc/yum.repos.d/oraclelinux-automation-manager-ol8.repo"
        section: ol8_automation
        option: enabled
        value: "0"
        mode: 0644

    - name: disable Oracle Linux Automation Manager 2.0 repository
      ini_file:
        path: "/etc/yum.repos.d/oraclelinux-automation-manager-ol8.repo"
        section: ol8_automation2
        option: enabled
        value: "0"
        mode: 0644

    - name: enable Oracle Linux Automation Manager 2.2 repository
      ini_file:
        path: "/etc/yum.repos.d/oraclelinux-automation-manager-ol8.repo"
        section: ol8_automation2.2
        option: enabled
        value: "1"
        mode: 0644

    - name: install Oracle Linux Automation Manager
      dnf:
        name: ol-automation-manager
        state: present
      environment: "{{ proxy_env }}"

    - name: edit unixsocket in /etc/redis.conf
      lineinfile:
        path: /etc/redis.conf
        regexp: '^unixsocket '
        insertafter: '^# unixsocketperm '
        line: unixsocket /var/run/redis/redis.sock

    - name: edit unixsocketperm in /etc/redis.conf
      lineinfile:
        path: /etc/redis.conf
        regexp: '^unixsocketperm '
        insertafter: '^unixsocket '
        line: unixsocketperm 775

    - name: configure CLUSTER_HOST_ID setting
      copy:
        dest: /etc/tower/conf.d/olam.py
        content: |
          CLUSTER_HOST_ID = "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
          DEFAULT_EXECUTION_QUEUE_NAME = 'execution'
          DEFAULT_CONTROL_PLANE_QUEUE_NAME = 'controlplane'
        owner: awx
        group: awx
        mode: '0640'

    - name: provision olam ansible container environment
      containers.podman.podman_image:
        name: container-registry.oracle.com/oracle_linux_automation_manager/olam-ee
      become_user: awx
      environment: "{{ proxy_env }}"

    - name: Generate an OpenSSL private key with a different size (2048 bits)
      community.crypto.openssl_privatekey:
        path: /etc/tower/tower.key
        size: 2048

    - name: Generate an OpenSSL Certificate Signing Request
      community.crypto.openssl_csr:
        path: /etc/tower/tower.csr
        privatekey_path: /etc/tower/tower.key

    - name: Generate a Self Signed OpenSSL certificate
      community.crypto.x509_certificate:
        path: /etc/tower/tower.crt
        privatekey_path: /etc/tower/tower.key
        csr_path: /etc/tower/tower.csr
        provider: selfsigned

    - name: remove default server section in nginx configuration
      template:
        src: ../templates/nginx.conf.tpl
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644

    - name: set firewall service rules
      ansible.posix.firewalld:
        zone: public
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - http
        - https

    - name: set firewall port rules
      ansible.posix.firewalld:
        zone: public
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - 27199/tcp

- hosts: control_nodes,execution_nodes
  collections:
    - ansible.posix
    - community.general
    - community.postgresql
    - community.crypto
  become: yes

  tasks:

    - name: get db ipaddress
      set_fact:
        db_node_ip: "{{ hostvars[groups['db_nodes'][0]]['ansible_default_ipv4']['address'] }}"

    - name: configure DATABASE settings
      copy:
        dest: /etc/tower/conf.d/db.py
        content: |
          DATABASES = {
              'default': {
                  'ATOMIC_REQUESTS': True,
                  'ENGINE': 'awx.main.db.profiled_pg',
                  'NAME': 'awx',
                  'USER': 'awx',
                  'PASSWORD': '{{ awx_pguser_password }}',
                  'HOST': '{{ db_node_ip }}',
                  'PORT': '5432',
              }
          }
        owner: awx
        group: awx
        mode: '0640'

    - name: check if awx setup
      stat:
        path: /var/lib/awx/.awx-setup
      register: awx_setup
      when: ( inventory_hostname == groups["control_nodes"][0] )

    - name: run awx-manage migrate
      shell: |
        awx-manage migrate
        touch /var/lib/awx/.awx-setup
      args:
        executable: /bin/bash
      become_user: awx
      register: awx_migrate
      when:
        - ( inventory_hostname == groups["control_nodes"][0] )
        - not awx_setup.stat.exists
      changed_when: awx_migrate is not search('already exists')

    - name: create awx superuser
      block:
        - name: set awx password
          expect:
            command: "awx-manage createsuperuser --username admin --email admin@example.com"
            responses:
              'Password:': "{{ olam_admin_password }}"
              'Password \(again\):': "{{ olam_admin_password }}"
          register: awx_password
          become_user: awx
          ignore_errors: yes
          changed_when: awx_password.stdout is not search('is already taken')
      when:
        - ( inventory_hostname == groups["control_nodes"][0] )
        - not awx_setup.stat.exists

    - debug:
        var: awx_password
      when:
        - ( inventory_hostname == groups["control_nodes"][0] )
        - not awx_setup.stat.exists

- hosts: control_nodes:execution_nodes:!control_nodes[0]
  collections:
    - ansible.posix
  become: yes

  tasks:

    - name: copy SECRET from control-node01 to all other hosts
      ansible.posix.synchronize:
        src: /etc/tower/SECRET_KEY
        dest: /etc/tower/SECRET_KEY
        owner: true
        group: true
        private_key: '/home/{{ username }}/.ssh/id_olam_rsa'
      delegate_to: "{{ groups['control_nodes'][0] }}"

- hosts: control_nodes,execution_nodes
  become: yes

  tasks:

    - name: create initial configuration in receptor
      template:
        src: ../templates/receptor.conf.tpl
        dest: /etc/receptor/receptor.conf
        owner: root
        group: root
        mode: '0644'

    - name: change work type to ansible-runner for execution node
      ansible.builtin.replace:
        path: /etc/receptor/receptor.conf
        regexp: 'worktype: local'
        replace: 'worktype: ansible-runner'
      when:
        - inventory_hostname in groups.execution_nodes
        - inventory_hostname not in groups.hop

    - name: add tcp-peers if present
      ansible.builtin.lineinfile:
        path: /etc/receptor/receptor.conf
        insertbefore: '^- control-service:'
        line: |
          - tcp-peer:
              address: {{ hostvars[item]['ansible_default_ipv4']['address'] }}:27199
              redial: true
      with_inventory_hostnames:
        - "{{ peers }}"
      when: peers is defined

    # - name: start receptor service
    #   systemd:
    #     name: "{{ item }}"
    #     state: started
    #     enabled: yes
    #   with_items:
    #     - receptor_awx

    - name: display receptor.conf contents
      command: cat receptor.conf chdir=/etc/receptor
      register: command_output

    - name: print to console
      debug:
        msg: "{{command_output.stdout_lines}}"

- hosts: control_nodes[0]
  become: yes

  tasks:

    - name: check if awx provisioned
      stat:
        path: /var/lib/awx/.awx-provisioned
      register: awx_provision

    - name: generate awx-manage script
      copy:
        dest: /var/lib/awx/awx_provision.sh
        content: |
            #!/bin/bash

            {% for item in groups['control_nodes'] %}
            awx-manage provision_instance --hostname={{ hostvars[item]['ansible_default_ipv4']['address'] }} --node_type=control
            awx-manage register_queue --queuename=controlplane --hostnames={{ hostvars[item]['ansible_default_ipv4']['address'] }}
            {% endfor %}
            {% for item in groups['execution_nodes'] %}
            awx-manage provision_instance --hostname={{ hostvars[item]['ansible_default_ipv4']['address'] }} --node_type={% if item in groups['hop'] %}hop{% else %}execution{% endif %}{{''}}
            {% endfor %}
            {% for item in groups['execution_nodes'] %}
            {% if item not in groups['hop'] %}
            awx-manage register_queue --queuename=execution --hostnames={{ hostvars[item]['ansible_default_ipv4']['address'] }}
            {% endif %}
            {% endfor %}
            awx-manage register_default_execution_environments
            awx-manage create_preload_data
            touch /var/lib/awx/.awx-provisioned
        owner: awx
        group: awx
        mode: '0700'

    - name: cat script
      shell: |
        cat /var/lib/awx/awx_provision.sh
      args:
        executable: /bin/bash
      become_user: awx
      register: provision_script

    - name: print script contents
      debug:
        msg: "{{ provision_script }}"

    - name: execute awx-manage provision script
      shell: |
        /var/lib/awx/awx_provision.sh
      args:
        executable: /bin/bash
      become_user: awx
      register: awx_provision_script
      changed_when: awx_provision_script is not search('already exists')

    - name: print awx_provision_script
      debug:
        msg: "{{ awx_provision_script }}"


- hosts: control_nodes,execution_nodes
  become: yes

  tasks:

    - name: run awx-manage peers
      shell: |
        awx-manage register_peers {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} --peers {{ hostvars[item]['ansible_default_ipv4']['address'] }}
      args:
        executable: /bin/bash
      become_user: awx
      register: awx_peers
      with_inventory_hostnames:
        - "{{ peers }}"
      when: ( peers is defined )
      delegate_to: "{{ groups['control_nodes'][0] }}"

    - name: print to awx_peers
      debug:
        msg: "{{awx_peers}}"

    - name: Enable and start ol-automation service
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - ol-automation-manager


